# Generated by Django 4.2 on 2025-04-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={}, max_length=150, validators=[django.core.validators.RegexValidator(message='Username hanya boleh berisi huruf, angka, spasi, dan karakter @/./+/-/_.', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
