# Generated by Django 4.2 on 2025-04-05 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimbel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('kuota_awal', models.PositiveIntegerField()),
                ('sisa_kuota', models.PositiveIntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimbels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bimbel',
                'verbose_name_plural': 'Bimbel',
                'ordering': ['-created_at'],
            },
        ),
    ]
