# Generated by Django 5.2 on 2025-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbelpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbel',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
