# Generated by Django 4.2 on 2025-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimbelpage', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
